version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    image: web:code
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    container_name: my_django_container